### PR TITLE
update for VectorInterface 0.4

### PR DESCRIPTION
**Pull request by lkdvos**

### CODE REVIEW

**Comment by lkdvos** [comment]
Should probably rerun CI now that VectorInterface is tagged

**Comment by Jutho** [comment]
We should probably wait for TensorOperations no? Currently this would give a dependency conflict?

**Comment by Jutho** [comment]
Strange error on Julia 1.6, but maybe we can also switch to PackageExtensionCompat ?

**Comment by lkdvos** [comment]
> Strange error on Julia 1.6, but maybe we can also switch to PackageExtensionCompat ?

I already did, but forgot to remove a `using Requires` somewhere, should be fixed now

**Pull request merged**
